// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPermissions() {
  return window['go']['main']['App']['CheckPermissions']();
}

export function ClearKeyboardBuffer() {
  return window['go']['main']['App']['ClearKeyboardBuffer']();
}

export function ClearScreenshotHistory() {
  return window['go']['main']['App']['ClearScreenshotHistory']();
}

export function ClearTextHistory() {
  return window['go']['main']['App']['ClearTextHistory']();
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GenerateRoomCode() {
  return window['go']['main']['App']['GenerateRoomCode']();
}

export function GetAppExecutablePath() {
  return window['go']['main']['App']['GetAppExecutablePath']();
}

export function GetBufferStatus() {
  return window['go']['main']['App']['GetBufferStatus']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDetailedPermissionStatus() {
  return window['go']['main']['App']['GetDetailedPermissionStatus']();
}

export function GetHotkeys() {
  return window['go']['main']['App']['GetHotkeys']();
}

export function GetInputMode() {
  return window['go']['main']['App']['GetInputMode']();
}

export function GetKeyboardBuffer() {
  return window['go']['main']['App']['GetKeyboardBuffer']();
}

export function GetPermissions() {
  return window['go']['main']['App']['GetPermissions']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetScreenshotByID(arg1) {
  return window['go']['main']['App']['GetScreenshotByID'](arg1);
}

export function GetScreenshotHistory() {
  return window['go']['main']['App']['GetScreenshotHistory']();
}

export function GetScreenshotSaveDir() {
  return window['go']['main']['App']['GetScreenshotSaveDir']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function GetTextHistory() {
  return window['go']['main']['App']['GetTextHistory']();
}

export function OpenPermissionSettings(arg1) {
  return window['go']['main']['App']['OpenPermissionSettings'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RecheckPermissions() {
  return window['go']['main']['App']['RecheckPermissions']();
}

export function RequestAllPermissions() {
  return window['go']['main']['App']['RequestAllPermissions']();
}

export function RequestPermission(arg1) {
  return window['go']['main']['App']['RequestPermission'](arg1);
}

export function ResetStatistics() {
  return window['go']['main']['App']['ResetStatistics']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveScreenshotToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveScreenshotToFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectScreenshotDirectory() {
  return window['go']['main']['App']['SelectScreenshotDirectory']();
}

export function SendText(arg1) {
  return window['go']['main']['App']['SendText'](arg1);
}

export function SetInputMode(arg1) {
  return window['go']['main']['App']['SetInputMode'](arg1);
}

export function SetScreenshotSaveDir(arg1) {
  return window['go']['main']['App']['SetScreenshotSaveDir'](arg1);
}

export function StartPermissionPolling(arg1) {
  return window['go']['main']['App']['StartPermissionPolling'](arg1);
}

export function ToggleInputMode() {
  return window['go']['main']['App']['ToggleInputMode']();
}

export function TypeBuffer() {
  return window['go']['main']['App']['TypeBuffer']();
}
