// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPermissions() {
  return window['go']['app']['App']['CheckPermissions']();
}

export function ClearHints() {
  return window['go']['app']['App']['ClearHints']();
}

export function ClearKeyboardBuffer() {
  return window['go']['app']['App']['ClearKeyboardBuffer']();
}

export function ClearScreenshotHistory() {
  return window['go']['app']['App']['ClearScreenshotHistory']();
}

export function ClearTextHistory() {
  return window['go']['app']['App']['ClearTextHistory']();
}

export function ClearTextOverlays() {
  return window['go']['app']['App']['ClearTextOverlays']();
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function GenerateRoomCode() {
  return window['go']['app']['App']['GenerateRoomCode']();
}

export function GetAppExecutablePath() {
  return window['go']['app']['App']['GetAppExecutablePath']();
}

export function GetBufferStatus() {
  return window['go']['app']['App']['GetBufferStatus']();
}

export function GetConnectionStatus() {
  return window['go']['app']['App']['GetConnectionStatus']();
}

export function GetDetailedPermissionStatus() {
  return window['go']['app']['App']['GetDetailedPermissionStatus']();
}

export function GetHotkeys() {
  return window['go']['app']['App']['GetHotkeys']();
}

export function GetInputMode() {
  return window['go']['app']['App']['GetInputMode']();
}

export function GetInvisibilityStatus() {
  return window['go']['app']['App']['GetInvisibilityStatus']();
}

export function GetKeyboardBuffer() {
  return window['go']['app']['App']['GetKeyboardBuffer']();
}

export function GetPermissions() {
  return window['go']['app']['App']['GetPermissions']();
}

export function GetPlatform() {
  return window['go']['app']['App']['GetPlatform']();
}

export function GetScreenshotByID(arg1) {
  return window['go']['app']['App']['GetScreenshotByID'](arg1);
}

export function GetScreenshotHistory() {
  return window['go']['app']['App']['GetScreenshotHistory']();
}

export function GetScreenshotSaveDir() {
  return window['go']['app']['App']['GetScreenshotSaveDir']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetStatistics() {
  return window['go']['app']['App']['GetStatistics']();
}

export function GetTextHistory() {
  return window['go']['app']['App']['GetTextHistory']();
}

export function IsInvisibilitySupported() {
  return window['go']['app']['App']['IsInvisibilitySupported']();
}

export function OpenPermissionSettings(arg1) {
  return window['go']['app']['App']['OpenPermissionSettings'](arg1);
}

export function QuitApp() {
  return window['go']['app']['App']['QuitApp']();
}

export function RecheckPermissions() {
  return window['go']['app']['App']['RecheckPermissions']();
}

export function RequestAllPermissions() {
  return window['go']['app']['App']['RequestAllPermissions']();
}

export function RequestPermission(arg1) {
  return window['go']['app']['App']['RequestPermission'](arg1);
}

export function ResetStatistics() {
  return window['go']['app']['App']['ResetStatistics']();
}

export function RestartApp() {
  return window['go']['app']['App']['RestartApp']();
}

export function SaveScreenshotToFile(arg1, arg2) {
  return window['go']['app']['App']['SaveScreenshotToFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SelectScreenshotDirectory() {
  return window['go']['app']['App']['SelectScreenshotDirectory']();
}

export function SendCursorClick(arg1, arg2) {
  return window['go']['app']['App']['SendCursorClick'](arg1, arg2);
}

export function SendCursorHide() {
  return window['go']['app']['App']['SendCursorHide']();
}

export function SendCursorMove(arg1, arg2) {
  return window['go']['app']['App']['SendCursorMove'](arg1, arg2);
}

export function SendCursorShow() {
  return window['go']['app']['App']['SendCursorShow']();
}

export function SendDrawClear() {
  return window['go']['app']['App']['SendDrawClear']();
}

export function SendDrawEnd(arg1, arg2) {
  return window['go']['app']['App']['SendDrawEnd'](arg1, arg2);
}

export function SendDrawMove(arg1, arg2) {
  return window['go']['app']['App']['SendDrawMove'](arg1, arg2);
}

export function SendDrawStart(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SendDrawStart'](arg1, arg2, arg3, arg4, arg5);
}

export function SendDrawUndo() {
  return window['go']['app']['App']['SendDrawUndo']();
}

export function SendHint(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SendHint'](arg1, arg2, arg3, arg4);
}

export function SendNotification(arg1, arg2) {
  return window['go']['app']['App']['SendNotification'](arg1, arg2);
}

export function SendText(arg1) {
  return window['go']['app']['App']['SendText'](arg1);
}

export function SendTextOverlay(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SendTextOverlay'](arg1, arg2, arg3, arg4);
}

export function SetInputMode(arg1) {
  return window['go']['app']['App']['SetInputMode'](arg1);
}

export function SetInvisibility(arg1) {
  return window['go']['app']['App']['SetInvisibility'](arg1);
}

export function SetScreenshotSaveDir(arg1) {
  return window['go']['app']['App']['SetScreenshotSaveDir'](arg1);
}

export function StartPermissionPolling(arg1) {
  return window['go']['app']['App']['StartPermissionPolling'](arg1);
}

export function ToggleInputMode() {
  return window['go']['app']['App']['ToggleInputMode']();
}

export function ToggleInvisibility() {
  return window['go']['app']['App']['ToggleInvisibility']();
}

export function TypeBuffer() {
  return window['go']['app']['App']['TypeBuffer']();
}
