// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CheckPermissions():Promise<Record<string, any>>;

export function ClearHints():Promise<void>;

export function ClearKeyboardBuffer():Promise<void>;

export function ClearScreenshotHistory():Promise<void>;

export function ClearTextHistory():Promise<void>;

export function ClearTextOverlays():Promise<void>;

export function Connect(arg1:string,arg2:number,arg3:string,arg4:string):Promise<app.ConnectionStatus>;

export function Disconnect():Promise<void>;

export function GenerateRoomCode():Promise<string>;

export function GetAppExecutablePath():Promise<string>;

export function GetBufferStatus():Promise<Record<string, any>>;

export function GetConnectionStatus():Promise<app.ConnectionStatus>;

export function GetDetailedPermissionStatus():Promise<Record<string, any>>;

export function GetHotkeys():Promise<Record<string, string>>;

export function GetInputMode():Promise<boolean>;

export function GetInvisibilityStatus():Promise<Record<string, any>>;

export function GetKeyboardBuffer():Promise<string>;

export function GetPermissions():Promise<Array<app.PermissionInfoJS>>;

export function GetPlatform():Promise<string>;

export function GetScreenshotByID(arg1:number):Promise<Record<string, any>>;

export function GetScreenshotHistory():Promise<Array<app.ScreenshotHistoryEntryJS>>;

export function GetScreenshotSaveDir():Promise<string>;

export function GetSettings():Promise<app.Settings>;

export function GetStatistics():Promise<app.Statistics>;

export function GetTextHistory():Promise<Array<app.TextHistoryEntry>>;

export function IsInvisibilitySupported():Promise<boolean>;

export function OpenPermissionSettings(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RecheckPermissions():Promise<Record<string, any>>;

export function RequestAllPermissions():Promise<Record<string, boolean>>;

export function RequestPermission(arg1:string):Promise<boolean>;

export function ResetStatistics():Promise<void>;

export function RestartApp():Promise<void>;

export function SaveScreenshotToFile(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:app.Settings):Promise<void>;

export function SelectScreenshotDirectory():Promise<string>;

export function SendCursorClick(arg1:number,arg2:number):Promise<void>;

export function SendCursorHide():Promise<void>;

export function SendCursorMove(arg1:number,arg2:number):Promise<void>;

export function SendCursorShow():Promise<void>;

export function SendDrawClear():Promise<void>;

export function SendDrawEnd(arg1:number,arg2:number):Promise<void>;

export function SendDrawMove(arg1:number,arg2:number):Promise<void>;

export function SendDrawStart(arg1:number,arg2:number,arg3:string,arg4:number,arg5:string):Promise<void>;

export function SendDrawUndo():Promise<void>;

export function SendHint(arg1:number,arg2:number,arg3:string,arg4:number):Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SendText(arg1:string):Promise<void>;

export function SendTextOverlay(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SetInputMode(arg1:boolean):Promise<boolean>;

export function SetInvisibility(arg1:boolean):Promise<boolean>;

export function SetScreenshotSaveDir(arg1:string):Promise<void>;

export function StartPermissionPolling(arg1:number):Promise<void>;

export function ToggleInputMode():Promise<boolean>;

export function ToggleInvisibility():Promise<boolean>;

export function TypeBuffer():Promise<void>;
